#!/bin/sh

# assumes /mnt/rootfs and /efi are already mounted
# verify currently running from @openwrt
if [ `findmnt --mountpoint / -o FSROOT -n` != "/@openwrt" ]; then
    echo "Can't upgrade when not running from @openwrt"
    exit 1
fi

if [ ! -f /tmp/openwrt-x86-64-generic-rootfs-kernel.tar.gz ]; then
    echo "No file /tmp/openwrt-x86-64-generic-rootfs-kernel.tar.gz"
    exit 1
fi

# remove any pre-existing @upgrade from prior failed upgrades
[ -d /mnt/rootfs/@upgrade ] && btrfs subvolume delete /mnt/rootfs/@upgrade
btrfs subvolume create /mnt/rootfs/@upgrade
tar -xzf /tmp/openwrt-x86-64-generic-rootfs-kernel.tar.gz -C /mnt/rootfs/@upgrade
#TODO: snapshot here as "reset to factory"?

# copy preserved files
#TODO: sysupgrade unpack by 80_mount_root would also keep any new lines from /etc/passwd /etc/group /etc/shadow
for f in `sysupgrade -l`; do
    mkdir -p /mnt/rootfs/@upgrade/`dirname $f`
    cp -P /mnt/rootfs/@openwrt/$f /mnt/rootfs/@upgrade/$f
done

# set grub env to boot @upgrade and reboot..
grub-editenv /efi/EFI/openwrt/grubenv set next_entry=openwrt-upgrade

echo "reboot to complete upgrade"
