#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2013-2020 OpenWrt.org

# just after fstab
START=12

boot() {
    local i='0'
    while uci -q get btrfs.@subvol[$i] > /dev/null; do
        local label=`uci -q get btrfs.@subvol[$i].label`
        local uuid=`uci -q get btrfs.@subvol[$i].uuid`
        local device=''
        if [ "$label" ]; then 
            device="LABEL=$label"
        elif [ "$uuid" ]; then 
            device="UUID=$uuid"
        fi

        local subvol=`uci get btrfs.@subvol[$i].subvol`
        local target=`uci get btrfs.@subvol[$i].target`
        if [ -z "$device" ]; then
            echo "missing device spec to mount $subvol in $target" > /dev/kmsg
        elif [ -z "$subvol" ]; then
            echo "missing subvol spec for $device in $target" > /dev/kmsg
        elif [ -z "$target" ]; then
            echo "missing target spec for $device subvol $subvol" > /dev/kmsg
        else
            mkdir -p $target
            mount $device $target -osubvol=$subvol
        fi
        i=`expr $i + 1`
    done

    local current=`findmnt --mountpoint / -o FSROOT -n`
    current=${current#/}
    echo "btrfs_slots: booted from $current" > /dev/kmsg
    if [ -e "/set_default" ]; then
        ln -sfT $current /mnt/rootfs/@openwrt
        rm /set_default
        echo "btrfs_slots: $current now set as default boot" > /dev/kmsg
    fi
}

start() {
    return 0
}

restart() {
    return 0
}

stop() {
    return 0
}
